backend:
  name: git-gateway
  branch: main

media_folder: "images/galeria"
public_folder: "/images/galeria"

collections:
  - name: "galeria"
    label: "Galería de Fotos"
    folder: "images/galeria"
    create: true
    fields:
      - { label: "Título de la foto", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
